### ISSUE TITLE
Instant Railgun Charge doesn't work.

### ISSUE THREAD

**Issue by ERENPROO** [Saniee/ULTRAKILLTrainer#3]
As said above, railgun charge cheat is not working. Am I doing something wrong or a bug?

**Comment by Saniee** [comment]
Could you perhaps tell me more? Like when did you want to enable the feature etc.?

**Comment by ERENPROO** [comment]
I enabled the feature after I was at the starting chamber of P-2. And another Cheat Table was at the background.

**Comment by Saniee** [comment]
Try enabling it without the other cheat table. It might cause the issue. If it still doesn't work ill look into it later.

**Comment by ERENPROO** [comment]
I'll try.

**Comment by ERENPROO** [comment]
Nope, still doesn't work. And Revolver charge is only working for Piercer. Marksman coins and Sharpshooter bullets still have cooldown. (I'm using Marksman in normal version, while Sharpshooter is Slab.)

**Comment by Saniee** [comment]
There might be also the possibility of the game code being different for each variation of the weapon. Even tho this is not in the de-compiled source code. If so this is a bug.

**Comment by Saniee** [comment]
So, I have launched up P-2 and tested around. Seems like the weapon code is the same across the weapons. So there is nothing wrong there. I did however came across the nailgun magnets not working. Other than that, any other feature worked fine. I am unsure why it doesn't work for you. And I am not sure how to fix it. The only thing I can suggest is to see if the cheat table isnt modified or corrupt in any way (Pretty much maybe try redownloading the table and see if the bug is still there.). 

I am sorry for this, but I can honestly do nothing. I will be sending an unlisted video of me trying the features out.

**Comment by ERENPROO** [comment]
Okay.

**Comment by Saniee** [comment]
https://youtu.be/MeJG3ErkrCA

**Comment by ERENPROO** [comment]
Oh so you solved it?!

**Comment by Saniee** [comment]
Since this bug was in the previous version. I am hoping it will not appear in the next update of the table for the new game version when I get to it.

**Comment by Saniee** [comment]
If it reappears, you can comment here again for me to reopen this issue.

**Comment by ERENPROO** [comment]
> Since this bug was in the previous version. I am hoping it will not appear in the next update of the table for the new game version when I get to it.

Okay.

**Comment by ERENPROO** [comment]
> If it reappears, you can comment here again for me to reopen this issue.

Understood.
